version: '3.9'

services:
  correcaminos_dev:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "443:443"
    links:
      - db_correcaminos_dev
    volumes:
      - .:/var/www/html/
      - ./config/php-dev/php:/usr/local/etc/php
    user: root
  db_correcaminos_dev:
    build:
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=19630306
      - MYSQL_DATABASE=sii_test
      - MYSQL_SSL_MODE=REQUIRED
    volumes:
      - data-db-test-correcaminos:/var/lib/mysql
  phpmyadmin_dev:
    build: 
      context: .
      dockerfile: dockerfile.phpmyadmin
    ports:
      - "8443:443"
    links:
      - db_correcaminos_dev
    environment:
      - PMA_HOST=db_correcaminos_dev
  smtpserver_dev:
    image: mailhog/mailhog:v1.0.1
    restart: always
    container_name: mailhog  # Nombre personalizado del contenedor
    ports:
      - "1025:1025"  # Puerto para SMTP
      - "8025:8025"  # Puerto para interfaz web


volumes:
  data-db-test-correcaminos: