version: '3.9'

services:
  correcaminos:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "443:443"
    links:
      - db_correcaminos
    volumes:
      - .:/var/www/html/
      - ./config/php-dev/php:/usr/local/etc/php
    user: root
  db_correcaminos:
    build:
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=19630306
      - MYSQL_SSL_MODE=REQUIRED
    volumes:
      - data-db-correcaminos:/var/lib/mysql
  phpmyadmin:
    build: 
      context: .
      dockerfile: dockerfile.phpmyadmin
    ports:
      - "8443:443"
    links:
      - db_correcaminos
    environment:
      - PMA_HOST=db_correcaminos

volumes:
  data-db-correcaminos: