INSERT INTO
    informacion_bancaria (
        id_banco,
        banco,
        sucursal,
        cuenta,
        rfc,
        costo_semestre,
        costo_examen,
        costo_constancias,
        costo_verano
    )
VALUES
    (
        0,
        'BANAMEX',
        '7006',
        '5252854',
        'TNM140723GFA',
        1750,
        750,
        50,
        15000,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL
    );