INSERT INTO
    carreras(
        id_carrera,
        nombre_carrera,
        clave_carrera,
        id_nivel_escolar,
        fecha_inicio,
        created_at,
        updated_at,
        deleted_at,
        created_by,
        updated_by,
        deleted_by
    )
VALUES
    (
        0,
        'Ingenieria en Sistemas Computacionales',
        'ISIC-2010-224',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    ),
    (
        0,
        'Ingenieria en Logistica',
        'ILOG-2009-202',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    ),
    (
        0,
        'Ingenieria Industrial',
        'IIND-2010-227',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    ),
    (
        0,
        'Ingenieria en Electromecanica',
        'IEME-2010-210',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    ),
    (
        0,
        'Ingenieria en Gestion Empresarial',
        'IGEM-2009-201',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    ),
    (
        0,
        'Contador Publico',
        'COPU-2010-205',
        1,
        SYSDATE(),
        SYSDATE(),
        SYSDATE(),
        NULL,
        'mike',
        'mike',
        NULL
    );