CREATE TABLE alumnos (
    id_alumno INT UNSIGNED AUTO_INCREMENT,
    no_control VARCHAR(9) UNIQUE NOT NULL,
    nombre VARCHAR(255),
    apellido_materno VARCHAR(255),
    apellido_paterno VARCHAR(255),
    curp VARCHAR(18) UNIQUE NOT NULL,
    id_reticula INT UNSIGNED,
    id_nivel_escolar int unsigned,
    becado_por VARCHAR(255),
    creditos_aprobados DECIMAL,
    creditos_cursados DECIMAL,
    estatus_alumno VARCHAR(255),
    estatus_alumno_anterior VARCHAR(255),
    opcion_titulacion VARCHAR(255),
    modalidad VARCHAR(255),
    created_at DATETIME,
    updated_at DATETIME,
    deleted_at DATETIME,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_by VARCHAR(255),
    PRIMARY KEY (id_alumno)
);