CREATE TABLE alumno_inf_academica (
    id_alumno int UNSIGNED,
    fecha_titulacion DATE,
    foto BLOB,
    nip INT,
    escuela_procedencia VARCHAR(255),
    folio INT,
    folio_probable INT,
    firma BLOB,
    periodo_ingreso_it VARCHAR(255),
    periodo_titulacion VARCHAR(255),
    periodos_revalidacion INT,
    plan_de_estudios VARCHAR(255),
    promedio_aritmetico_acumulado DECIMAL,
    promedio_final_alcanzado DECIMAL,
    promedio_periodo_anterior DECIMAL,
    semestre INT,
    tipo_alumno VARCHAR(255),
    tipo_escuela INT,
    tipo_ingreso INT,
    tipo_servicio_medico VARCHAR(255),
    ultimo_periodo_inscrito VARCHAR(255),
    indice_reprobacion_acumulado DECIMAL
);