CREATE TABLE personal_datos_complementarios(
  id_personal INT(11) UNSIGNED,
  acta_nacimiento_ano INT,
  acta_nacimiento_foja INT,
  acta_nacimiento_libro VARCHAR(255),
  acta_nacimiento_numero INT,
  ano_clase INT,
  ano_inicio_estudios INT,
  ano_termino_estudios INT,
  codigo_postal_empleado INT(7),
  colonia_empleado VARCHAR(255),
  conyuge VARCHAR(255),
  madre VARCHAR(255),
  padre VARCHAR(255),
  pais VARCHAR(255),
  pasaporte INT,
  pasaporte_puesto_autorizado VARCHAR(255),
  pasaporte_vigencia_fin DATE,
  pasaporte_vigencia_inicio DATE,
  estado_civil VARCHAR(255),
  hijos INT,
  localidad VARCHAR(255),
  lugar_nacimiento INT,
  municipio_empleado VARCHAR(255),
  nacionalidad VARCHAR(255),
  sexo_empleado VARCHAR(255)
);